name: Legal Informatics and Forensic Science
url: http://lifs.hallym.ac.kr

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: rogue

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
#  - key: staff
#    name: Staff
#  - key: postdoc
#    name: Researchers
  - key: grad
    name: Graduate Students
  - key: ugrad
    name: Undergraduate Students
  - key: ugrad-alum
    name: Past Undergraduate Students
  - key: collab
    name: Collaborators
  - key: alum
    name: Alumni

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /#people
  - title: Research
    link: /html/research.html
  - title: Publications
    link: /html/publications.html
  - title: Code
    link: /html/code.html
  - title: Resources
    link: /html/resources.html
